In [ ]:
# This R environment comes with many helpful analytics packages installed
# It is defined by the kaggle/rstats Docker image: https://github.com/kaggle/docker-rstats
# For example, here's a helpful package to load

library(tidyverse) # metapackage of all tidyverse packages

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

list.files(path = "../input")

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Importing Library

Di notebook ini saya akan mempraktikkan dasar-dasar dari penggunaan library NumPy

In [1]:
import numpy as np

# Pengantar Numpy

In [2]:
# ini contoh dari membuat 1D array di NumPy
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [3]:
arr2 = np.array([[10, 20], [30, 40]])
print(arr2)

[[10 20]
 [30 40]]


In [4]:
print(type(arr2))

<class 'numpy.ndarray'>


In [5]:
np.array([1, 2, 'a'])

array(['1', '2', 'a'], dtype='<U21')

In [6]:
np.array([1, 2, 3.2])

array([1. , 2. , 3.2])

In [7]:
np.random.rand(1, 10, 10)

array([[[0.97533179, 0.059884  , 0.42782572, 0.51281028, 0.51816976,
         0.86423375, 0.55048621, 0.53947971, 0.99102546, 0.88147658],
        [0.86292411, 0.87385098, 0.85957594, 0.03295591, 0.67950939,
         0.65163341, 0.90070398, 0.65929549, 0.01265546, 0.48955348],
        [0.92321958, 0.08496933, 0.79276421, 0.52214928, 0.68110319,
         0.7343239 , 0.84885269, 0.47930286, 0.08328416, 0.91945089],
        [0.71349404, 0.99480072, 0.4877556 , 0.95400596, 0.00685566,
         0.82311847, 0.04978836, 0.63531805, 0.95752813, 0.58390019],
        [0.71632091, 0.54158175, 0.19558746, 0.44991776, 0.5104589 ,
         0.31355523, 0.66090716, 0.36381355, 0.20089939, 0.35219976],
        [0.03438509, 0.15266075, 0.88972668, 0.0205585 , 0.52428175,
         0.49650808, 0.40227634, 0.42148101, 0.24594568, 0.82875534],
        [0.6585807 , 0.60488018, 0.48449033, 0.20599453, 0.18156107,
         0.60494498, 0.49644305, 0.99956683, 0.46403759, 0.28051158],
        [0.82063194, 0.2089

In [8]:
arr2.shape

(2, 2)

In [9]:
arr2.size

4

In [10]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((5, 3), 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])